In [1]:
import numpy as np
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt 
import warnings 
warnings.filterwarnings('ignore')

In [2]:
#datasets
terrorist = pd.read_csv('datasets\\Global_terrorist.csv', encoding='ISO-8859-1')
terrorist

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
0,197000000001,1970,7,2,NaN,0,NaN,58,Dominican Republic,2,...,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
1,197000000002,1970,0,0,NaN,0,NaN,130,Mexico,1,...,NaN,NaN,NaN,NaN,PGIS,0,1,1,1,NaN
2,197001000001,1970,1,0,NaN,0,NaN,160,Philippines,5,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
3,197001000002,1970,1,0,NaN,0,NaN,78,Greece,8,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
4,197001000003,1970,1,0,NaN,0,NaN,101,Japan,4,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181686,201712310022,2017,12,31,NaN,0,NaN,182,Somalia,11,...,NaN,"""Somalia: Al-Shabaab Militants Attack Army Che...","""Highlights: Somalia Daily Media Highlights 2 ...","""Highlights: Somalia Daily Media Highlights 1 ...",START Primary Collection,0,0,0,0,NaN
181687,201712310029,2017,12,31,NaN,0,NaN,200,Syria,10,...,NaN,"""Putin's 'victory' in Syria has turned into a ...","""Two Russian soldiers killed at Hmeymim base i...","""Two Russian servicemen killed in Syria mortar...",START Primary Collection,-9,-9,1,1,NaN
181688,201712310030,2017,12,31,NaN,0,NaN,160,Philippines,5,...,NaN,"""Maguindanao clashes trap tribe members,"" Phil...",NaN,NaN,START Primary Collection,0,0,0,0,NaN
181689,201712310031,2017,12,31,NaN,0,NaN,92,India,6,...,NaN,"""Trader escapes grenade attack in Imphal,"" Bus...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
181690,201712310032,2017,12,31,NaN,0,NaN,160,Philippines,5,...,NaN,"""Security tightened in Cotabato following IED ...","""Security tightened in Cotabato City,"" Manila ...",NaN,START Primary Collection,-9,-9,0,-9,NaN

In [3]:
terrorist.columns

Index(['eventid', 'iyear', 'imonth', 'iday', 'approxdate', 'extended',
       'resolution', 'country', 'country_txt', 'region',
       ...
       'addnotes', 'scite1', 'scite2', 'scite3', 'dbsource', 'INT_LOG',
       'INT_IDEO', 'INT_MISC', 'INT_ANY', 'related'],
      dtype='object', length=135)

<h1>MIDDLE EAST & NORTH AFRICA BOMBING/EXPLOSION</h1>

In [4]:
#filtering data into smaller scope

filter1 = terrorist[terrorist['region_txt'] == 'Middle East & North Africa']

filter2 = filter1[filter1['attacktype1_txt'] == 'Bombing/Explosion']

filter3 = filter2[filter2['nkill'] >= 10 ]

filter4 = filter3[filter3['iyear'] >= 2000]

<h1>DATA AGGREGATION</h1><i>means collecting and summarizing data from multiple sources</i>

In [5]:
#aggregating data

ME_terror = filter4.groupby(['latitude', 'longitude']).size().reset_index(name = 'incident_count')
ME_terror

      latitude  longitude  incident_count
0    12.743795  44.843678               1
1    12.760069  44.890266               1
2    12.825647  44.846416              12
3    12.832581  45.027071               1
4    12.867085  44.981911               6
..         ...        ...             ...
517  38.720489  35.482597               1
518  39.798509  32.805613               1
519  39.916839  44.044637               1
520  39.930771  32.767540               3
521  41.106178  28.689863              10

[522 rows x 3 columns]

<h1>Visualization of Geospatial using FOLIUM</h1>

In [6]:
import folium
from folium.plugins import HeatMap

In [7]:
heat_df = ME_terror[['latitude', 'longitude', 'incident_count']].values.tolist()

In [8]:
my_map = folium.Map(location = [45.9432, 24.9668], zoom_start = 4)
HeatMap(heat_df).add_to(my_map)
my_map

Regional Analysis<br/>
Crime/Attack Analysis<br/>
Causality Analysis <br/>
Nationality Analysis<br/>

<h1>REGIONAL ANALYSIS</h1>

<h3>Which region has the highest number of facility/infrastructure attacks in asia?</h3>

<h1>South Asia</h1>

In [100]:
south_a1 = terrorist[terrorist['region_txt'] == 'South Asia']

south_a2 = south_a1[south_a1['attacktype1_txt'] == 'Facility/Infrastructure Attack']

In [101]:
#aggregating data

south_a = south_a2.groupby(['latitude', 'longitude']).size().reset_index(name = 'incident_count')

In [102]:
south = south_a[['latitude', 'longitude', 'incident_count']].values.tolist()
print(south_a.count())

latitude          1436
longitude         1436
incident_count    1436
dtype: int64

<h1>East Asia</h1>

In [103]:
east_a1 = terrorist[terrorist['region_txt'] == 'East Asia']

east_a2 = east_a1[east_a1['attacktype1_txt'] == 'Facility/Infrastructure Attack']

In [104]:
east_a = east_a2.groupby(['latitude', 'longitude']).size().reset_index(name = 'incident_count')
east_a = east_a.dropna(subset=['latitude', 'longitude'])

In [105]:
east = east_a[['latitude', 'longitude', 'incident_count']].values.tolist()
print(east_a.count())

latitude          69
longitude         69
incident_count    69
dtype: int64

<h1>SouthEast Asia</h1>

In [106]:
s_east_a1 = terrorist[terrorist['region_txt'] == 'Southeast Asia']

s_east_a2 = s_east_a1[s_east_a1['attacktype1_txt'] == 'Facility/Infrastructure Attack']

In [107]:
s_east_a = s_east_a2.groupby(['latitude', 'longitude']).size().reset_index(name = 'incident_count')
s_east_a = s_east_a.dropna(subset=['latitude', 'longitude'])

In [108]:
southeast = s_east_a[['latitude', 'longitude', 'incident_count']].values.tolist()
print(s_east_a.count())

latitude          680
longitude         680
incident_count    680
dtype: int64

<h1>Central Asia</h1>

In [109]:
c_a1 = terrorist[terrorist['region_txt'] == 'Central Asia']

c_a2 = c_a1[c_a1['attacktype1_txt'] == 'Facility/Infrastructure Attack']

In [110]:
c_a = c_a2.groupby(['latitude', 'longitude']).size().reset_index(name = 'incident_count')
c_a = c_a.dropna(subset=['latitude', 'longitude'])

In [111]:
central = c_a[['latitude', 'longitude', 'incident_count']].values.tolist()
print(c_a.count())

latitude          18
longitude         18
incident_count    18
dtype: int64

In [134]:
my_map = folium.Map(location = [20.0, 100.0], zoom_start = 3.5)

HeatMap(south).add_to(my_map)
HeatMap(east).add_to(my_map)
HeatMap(southeast).add_to(my_map)
HeatMap(central).add_to(my_map)
my_map

<h2>South Asia has the most Facility/Infrastructure Attack in Asia</h2>

<i>In the 2000s, Facility/Infrastructure Attacks were widespread in South Asia, largely driven by ongoing insurgencies, militant groups, and the global war on terror. These groups often saw infrastructure as a way to challenge state power, disrupt economic systems, and gain attention for their causes.</i>

<h1>CASUALITIES ANALYSIS</h1>

<h3>Which attack caused the most deaths? Bombing, Assault, Assassination</h3>

In [27]:
terrorist['attacktype1_txt'].value_counts()

attacktype1_txt
Bombing/Explosion                      88255
Armed Assault                          42669
Assassination                          19312
Hostage Taking (Kidnapping)            11158
Facility/Infrastructure Attack         10356
Unknown                                 7276
Unarmed Assault                         1015
Hostage Taking (Barricade Incident)      991
Hijacking                                659
Name: count, dtype: int64

In [48]:
terrorist['region_txt'].value_counts()

region_txt
Middle East & North Africa     50474
South Asia                     44974
South America                  18978
Sub-Saharan Africa             17550
Western Europe                 16639
Southeast Asia                 12485
Central America & Caribbean    10344
Eastern Europe                  5144
North America                   3456
East Asia                        802
Central Asia                     563
Australasia & Oceania            282
Name: count, dtype: int64

In [147]:
b_e1 = terrorist[terrorist['attacktype1_txt'] == 'Bombing/Explosion']

b_e2 = b_e1[b_e1['nkill'] >= 1 ]

In [148]:
b_e = b_e2.groupby(['latitude', 'longitude']).size().reset_index(name = 'incident_count')
b_e = b_e.dropna(subset=['latitude', 'longitude'])

In [149]:
heatdf = b_e[['latitude', 'longitude', 'incident_count']].values.tolist()

In [151]:
print(b_e.count())
my_map = folium.Map(location = [40.0, 40.0], zoom_start = 2)
HeatMap(heatdf).add_to(my_map)
my_map

latitude          9285
longitude         9285
incident_count    9285
dtype: int64

In [152]:
a_a1 = terrorist[terrorist['attacktype1_txt'] == 'Armed Assault']

a_a2 = a_a1[a_a1['nkill'] >= 1 ]

In [153]:
a_a = a_a2.groupby(['latitude', 'longitude']).size().reset_index(name = 'incident_count')
a_a = a_a.dropna(subset=['latitude', 'longitude'])

In [154]:
heatdf = a_a[['latitude', 'longitude', 'incident_count']].values.tolist()

In [155]:
print(a_a.count())
my_map = folium.Map(location = [40.0, 40.0], zoom_start = 2)
HeatMap(heatdf).add_to(my_map)
my_map

latitude          13435
longitude         13435
incident_count    13435
dtype: int64

In [156]:
a1 = terrorist[terrorist['attacktype1_txt'] == 'Assassination']

a2 = a1[a1['nkill'] >= 1 ]

In [157]:
a = a2.groupby(['latitude', 'longitude']).size().reset_index(name = 'incident_count')
a = a.dropna(subset=['latitude', 'longitude'])

In [158]:
heatdf = a[['latitude', 'longitude', 'incident_count']].values.tolist()

In [160]:
print(a.count())
my_map = folium.Map(location = [40.0, 40.0], zoom_start = 2)
HeatMap(heatdf).add_to(my_map)
my_map

latitude          5505
longitude         5505
incident_count    5505
dtype: int64

<h1>Armed Assault has the most deaths </h1>

<h1>CRIME/ATTACK ANALYSIS</h1>

In [210]:
armed_a1 = terrorist[terrorist['attacktype1_txt'] == 'Armed Assault']
armed_a2 = armed_a1[armed_a1['nkill'] > 1]

In [211]:
armed_a = armed_a2.groupby(['latitude', 'longitude']).size().reset_index(name='incident_count')
heatdf = armed_a[['latitude', 'longitude', 'incident_count']].values.tolist()

In [212]:
print(armed_a.count())
my_map = folium.Map(location=[20, 5], zoom_start=2)
HeatMap(heatdf).add_to(my_map)
my_map

latitude          9359
longitude         9359
incident_count    9359
dtype: int64

<h1>NATIONALITY ANALYSIS</h1>

In [162]:
terrorist['natlty1_txt'].value_counts()

natlty1_txt
Iraq                                  24113
Pakistan                              13900
India                                 12098
Afghanistan                           10931
Colombia                               7922
                                      ...
Commonwealth of Independent States        1
St. Lucia                                 1
Saba (Netherlands Antilles)               1
Tuvalu                                    1
Marshall Islands                          1
Name: count, Length: 215, dtype: int64

In [177]:
assa = terrorist[terrorist['attacktype1_txt'] == 'Assassination']
u_s = assa[assa['natlty1_txt'] == 'United States']

In [178]:
assa_us = u_s.groupby(['latitude', 'longitude']).size().reset_index(name='incident_count')

In [179]:
heatdf = assa_us[['latitude', 'longitude', 'incident_count']].values.tolist()

In [180]:
print(assa_us.count())
my_map = folium.Map(location=[33.0, 43.0], zoom_start= 3)
HeatMap(heatdf).add_to(my_map)
my_map

latitude          163
longitude         163
incident_count    163
dtype: int64